INSERT IGNORE INTO site_settings (setting_key, setting_value, created_at, updated_at) VALUES
('SHIPPING_FEE_DEFAULT', '30000', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('FREE_SHIPPING_THRESHOLD', '500000', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
